baseurl: '/'
permalink: pretty
# not used
# title: 'UFO Hibachi Express'

logo:
  mobile: "images/logo/logo-new.png"
  mobile_height: "85px"
  mobile_width: "270px"
  desktop: "images/logo/logo-new.png"
  desktop_height: "85px"
  desktop_width: "270px"

home: 
  limit_services: 6

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
